# Generated by Django 3.0.8 on 2020-08-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200803_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nutrition_grade',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
