# Generated by Django 3.0.8 on 2020-08-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200807_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brands',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='stores',
            field=models.CharField(max_length=100),
        ),
    ]
