# Generated by Django 3.0.8 on 2020-08-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('status', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'ordering': ['first_name'],
            },
        ),
    ]
