# Generated by Django 3.0.8 on 2020-08-08 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0006_auto_20200808_1518'),
        ('substitute', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='substitutes',
            new_name='substitute',
        ),
        migrations.AlterField(
            model_name='substitute',
            name='user_subst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subst', to=settings.AUTH_USER_MODEL),
        ),
    ]
